apiVersion: v2
version: 0.1.0
name: external-secrets-operator
description: "Installs external-secrets-operator, including the necessary network policies when required"
dependencies:
  - name: external-secrets
    version: 1.3.2
    repository: "https://charts.external-secrets.io/"
